### ISSUE TITLE
Black screen when reforming caravan with Setup-Camp.

### ISSUE THREAD

**Issue by Canute00** [RimWorld-CCL-Reborn/BetterMiniMap#14]
Setup-camp
https://github.com/Syrchalis/SetUpCamp
When you try to reform the caravan from a temp. map made from Setup-camp.
The world screen turn's black and you get a repeating error, only shown at the log file, since you don't see anything anymore at the game itself.
I can't say if this happen on vanilla temp. maps too.

**Comment by notfood** [comment]
It happens on vanilla maps as well as the only mod loaded.
To reproduce:
1. Land (naked).
2. WorldTab -> Make Caravan (select everything)
3. Abandon Settlement. Screen goes black.

It will always error. Happens on every map destroy.

**Comment by AaronCRobinson** [comment]
Thanks for the example notfood. I tried to recreate this with the current build and was unable to. I see you fix too which doesn't seem to be incorporated but if it shows up again, I will check this again. Cheers.
