### ISSUE TITLE
KeyBinding

### ISSUE THREAD

**Issue by SabitaUsagi** [RimWorld-CCL-Reborn/BetterMiniMap#15]
I desperately need to change the KeyBinding for this, and I can not find it in Overlay.Xml

**Comment by SabitaUsagi** [comment]
Actually what i think is happening is that K is your F9, and that works to toggle visibility of the map controls back and forth. 
While M is F8 and toggles the Visibilty of the minimap itself off, but not back on.

**Comment by AaronCRobinson** [comment]
Updated to 1.3: https://github.com/RimWorld-CCL-Reborn/BetterMiniMap/releases/tag/v1.3.0

If you see the bug again, please let me know. I can investigate this a bit and look into allowing key bindings to change.

**Comment by AaronCRobinson** [comment]
https://github.com/RimWorld-CCL-Reborn/BetterMiniMap/releases/tag/v1.3.1

Exposes key bindings as "toggleMiniMap" and "toggleMiniMapControls". You will need to open and close the settings to get them to save to the config file and currently, you can only manually edit them in the config file.
