### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by MIC132** [RimWorld-CCL-Reborn/BetterMiniMap#16]
All of my settings (from which things are shown on the minimap, to sizes/colors) don't seem to save between play sessions.

**Comment by MIC132** [comment]
Settings still aren't saving after the latest update.

**Comment by MIC132** [comment]
Actually, I did some testing, and apparently the settings get saved (they appear in the relevant config file), but not only do they reset if you open the settings dialog for this mod in-game again, they also simply don't appear to affect the minimap until you re-change them again while the game is running..

**Comment by Alis31x** [comment]
the same problem, the settings are not saved, please fix it

**Comment by AaronCRobinson** [comment]
Updated to 1.3: https://github.com/RimWorld-CCL-Reborn/BetterMiniMap/releases/tag/v1.3.0

If you see the bug again, please let me know. Hopefully, I will have some time to play a bit soon and investigate this.

**Comment by AaronCRobinson** [comment]
https://github.com/RimWorld-CCL-Reborn/BetterMiniMap/releases/tag/v1.3.1

Fixed. Thanks for bringing this to my attention even though it has taken so long for me to find time to code.
