### ISSUE TITLE
Add Overlay for Tiberium

### ISSUE THREAD

**Issue by AaronCRobinson** [RimWorld-CCL-Reborn/BetterMiniMap#7]

**Comment by DoctorVanGogh** [comment]
Suggestion: Add overlay for "generic ~~extra~~ material X" -don't specialize too much ;)

**Comment by AaronCRobinson** [comment]
Hey DoctorVanGogh, Talking to Tele on implementing this, we were able to quickly put something into the mod. 

Here is the commit: https://github.com/AaronCRobinson/BetterMiniMap/commit/268037612aee5439f1dedf289d12190dcb932c0c 

However, we think long term it would be better to do something like you mention where the overlays can be extended via xml definitions. Do you have some examples/reference I could look at for writing my own Defs and managing them?

I can edit the description to be something like `XML Generic OverlayDef format` or something too.

**Comment by DoctorVanGogh** [comment]
I'm doing something similar yet entirely different with Omni Core Drill. Taking arbitrary mod added stuff and potentially offering recipes for them. Just you want colored pixels ;)

Basically if you come up with some definition scheme like
`Mod [1] <-> [n] Overlay [n] <-> [m] thing based predicate`

### Ideas
- Come up with some configurable definition syntax `[DefName] -> [Color]`
- Store those "chunks" of definitions per mod somewhere (in a cloud?).
  - On steam you could use `ISteamUGC.AddItemKeyValueTag` - but key & values are limited to 255 characters each
  - Need a non steam option. Some directory file at a well defined location with links to available chunks?

### Alternative
- define an entirely _new_ type of `def`? `TerrainOverlayDef`
- Allow mods to define their own mapping?
- supply some predefined maps yourself?

**Comment by AaronCRobinson** [comment]
This should be finalized in 937654ea1e65ae47402382cb5bf4141f1eb33beb. Waiting for testing from Telefonmast via Discord before I will move forward with merging the branch in. 

Closing out the general "feature request" here and looking to open new tickets/issues against the `OverlayDef` implementation specifically.
